[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    tzapu/WiFiManager@^2.0.17
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    esphome/AsyncTCP-esphome@^2.1.4
build_flags =
    -D BOARD_ESP32

[env:lolin_d32]
platform = espressif32
board = lolin_d32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    tzapu/WiFiManager@^2.0.17
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    esphome/AsyncTCP-esphome@^2.1.4
build_flags =
    -D BOARD_ESP32

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    tzapu/WiFiManager@^2.0.17
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    esphome/AsyncTCP-esphome@^2.1.4
build_flags =
    -D BOARD_ESP32
